# Versão do MongoDB que o Flapdoodle vai baixar
spring.mongodb.embedded.version=6.0.5

# Onde os dados serão salvos (Pasta no root do projeto)
spring.mongodb.embedded.storage.database-dir=./mongodb-data

# Porta padrão para o seu back-end conectar
spring.data.mongodb.port=27017

security.jwt.secret=bookShelfLibrarySystemJwtSecretKeyVeryLongAndSecureForHS512DemoTCCUMC2026ThisIs512BitsBase64EquivalentWhenPaddedCorrectly86400000
security.jwt.expiration=86400000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true