spring.application.name=demo
spring.profiles.active=mongo

security.jwt.secret=bookShelfLibrarySystemJwtSecretKeyVeryLongAndSecureForHS512DemoUMC2026ThisIs512BitsBase64EquivalentWhenPaddedCorrectly86400000
security.jwt.expiration=86400000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true


# Silencia pacotes específicos que geram muito lixo visual
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.mongodb.driver=WARN
