# Versão do MongoDB que o Flapdoodle vai baixar
spring.mongodb.embedded.version=6.0.5

# Onde os dados serão salvos (Pasta no root do projeto)
spring.mongodb.embedded.storage.database-dir=./mongodb-data

spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb://localhost:27017/biblioteca

security.jwt.secret=bookShelfLibrarySystemJwtSecretKeyVeryLongAndSecureForHS512DemoUMC2026ThisIs512BitsBase64EquivalentWhenPaddedCorrectly86400000
security.jwt.expiration=86400000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

# Define o nível geral como INFO (esconde os DEBUGs do Spring)
logging.level.root=INFO

# Silencia pacotes específicos que geram muito lixo visual
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.mongodb.driver=WARN

logging.level.br.umc.demo=INFO
