spring.application.name=demo
spring.profiles.active=mongo

# Actuator
management.endpoints.web.exposure.include=mappings,health,info
management.endpoint.health.show-details=always

security.jwt.secret=bookShelfLibrarySystemJwtSecretKeyVeryLongAndSecureForHS512DemoTCCUMC2026ThisIs512BitsBase64EquivalentWhenPaddedCorrectly86400000
security.jwt.expiration=86400000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true


# Silencia pacotes específicos que geram muito lixo visual
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.mongodb.driver=WARN

# Se quiser manter APENAS os seus logs (AuthController, etc) como INFO:
logging.level.br.umc.demo=INFO
